name: stripe_js
description: Experimental package:js bindings for Stripe
version: 2.0.0
homepage: https://github.com/apptreesoftware/stripe_js
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: ^0.6.1

dev_dependencies:
  test: ^1.0.0
